# Server Port
server.port=8081

# Keycloak base URL
keycloak.auth-server-url=http://localhost:8080

# Spring Security OAuth2 - Client Registration (Keycloak)
spring.security.oauth2.client.registration.keycloak.client-id=placeholder-client-id-base
spring.security.oauth2.client.registration.keycloak.client-secret=APE7Jo7L22EY8yTKh50v6B82nQ8l3f24
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/{realmName}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

# Spring Security OAuth2 - Provider (Keycloak)
spring.security.oauth2.client.provider.keycloak.issuer-uri=${keycloak.auth-server-url}/realms/{realmName}
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.keycloak=DEBUG

# Tenants configuration (custom structure, to parse manually or via @ConfigurationProperties)
tenants.plexus.realm=plexus-realm
tenants.plexus.client-id=mi-app-plexus
tenants.plexus.client-secret=APE7Jo7L22EY8yTKh50v6B82nQ8l3f24

tenants.inditex.realm=inditex-realm
tenants.inditex.client-id=mi-app-inditex
tenants.inditex.client-secret=5LR8rwO0VLFpog0lCrxrODfxlwQEEj7g
